# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#       This is an auto-generated file!       #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #


# TGramBot - Partially Auto-generated Telegram Bot Api Library Python
# Copyright (C) 2022  Anand <anandpskerala@gmail.com>

# TGramBot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# TGramBot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from .tg_types import (
    Update,
    WebhookInfo,
    User,
    Chat,
    Message,
    MessageId,
    MessageEntity,
    PhotoSize,
    Animation,
    Audio,
    Document,
    Video,
    VideoNote,
    Voice,
    Contact,
    Dice,
    PollOption,
    PollAnswer,
    Poll,
    Location,
    Venue,
    WebAppData,
    ProximityAlertTriggered,
    MessageAutoDeleteTimerChanged,
    VideoChatScheduled,
    VideoChatStarted,
    VideoChatEnded,
    VideoChatParticipantsInvited,
    UserProfilePhotos,
    File,
    WebAppInfo,
    ReplyKeyboardMarkup,
    KeyboardButton,
    KeyboardButtonPollType,
    ReplyKeyboardRemove,
    InlineKeyboardMarkup,
    InlineKeyboardButton,
    LoginUrl,
    CallbackQuery,
    ForceReply,
    ChatPhoto,
    ChatInviteLink,
    ChatAdministratorRights,
    ChatMember,
    ChatMemberOwner,
    ChatMemberAdministrator,
    ChatMemberMember,
    ChatMemberRestricted,
    ChatMemberLeft,
    ChatMemberBanned,
    ChatMemberUpdated,
    ChatJoinRequest,
    ChatPermissions,
    ChatLocation,
    BotCommand,
    BotCommandScope,
    BotCommandScopeDefault,
    BotCommandScopeAllPrivateChats,
    BotCommandScopeAllGroupChats,
    BotCommandScopeAllChatAdministrators,
    BotCommandScopeChat,
    BotCommandScopeChatAdministrators,
    BotCommandScopeChatMember,
    MenuButton,
    MenuButtonCommands,
    MenuButtonWebApp,
    MenuButtonDefault,
    ResponseParameters,
    InputMedia,
    InputMediaPhoto,
    InputMediaVideo,
    InputMediaAnimation,
    InputMediaAudio,
    InputMediaDocument,
    InputFile,
    Sticker,
    StickerSet,
    MaskPosition,
    InlineQuery,
    InlineQueryResult,
    InlineQueryResultArticle,
    InlineQueryResultPhoto,
    InlineQueryResultGif,
    InlineQueryResultMpeg4Gif,
    InlineQueryResultVideo,
    InlineQueryResultAudio,
    InlineQueryResultVoice,
    InlineQueryResultDocument,
    InlineQueryResultLocation,
    InlineQueryResultVenue,
    InlineQueryResultContact,
    InlineQueryResultGame,
    InlineQueryResultCachedPhoto,
    InlineQueryResultCachedGif,
    InlineQueryResultCachedMpeg4Gif,
    InlineQueryResultCachedSticker,
    InlineQueryResultCachedDocument,
    InlineQueryResultCachedVideo,
    InlineQueryResultCachedVoice,
    InlineQueryResultCachedAudio,
    InputMessageContent,
    InputTextMessageContent,
    InputLocationMessageContent,
    InputVenueMessageContent,
    InputContactMessageContent,
    InputInvoiceMessageContent,
    ChosenInlineResult,
    SentWebAppMessage,
    LabeledPrice,
    Invoice,
    ShippingAddress,
    OrderInfo,
    ShippingOption,
    SuccessfulPayment,
    ShippingQuery,
    PreCheckoutQuery,
    PassportData,
    PassportFile,
    EncryptedPassportElement,
    EncryptedCredentials,
    PassportElementError,
    PassportElementErrorDataField,
    PassportElementErrorFrontSide,
    PassportElementErrorReverseSide,
    PassportElementErrorSelfie,
    PassportElementErrorFile,
    PassportElementErrorFiles,
    PassportElementErrorTranslationFile,
    PassportElementErrorTranslationFiles,
    PassportElementErrorUnspecified,
    Game,
    CallbackGame,
    GameHighScore
)

__all__ = [
    'Update', 'WebhookInfo', 'User', 'Chat',
    'Message', 'MessageId', 'MessageEntity', 'PhotoSize',
    'Animation', 'Audio', 'Document', 'Video',
    'VideoNote', 'Voice', 'Contact', 'Dice',
    'PollOption', 'PollAnswer', 'Poll', 'Location',
    'Venue', 'WebAppData', 'ProximityAlertTriggered', 'MessageAutoDeleteTimerChanged',
    'VideoChatScheduled', 'VideoChatStarted', 'VideoChatEnded', 'VideoChatParticipantsInvited',
    'UserProfilePhotos', 'File', 'WebAppInfo', 'ReplyKeyboardMarkup',
    'KeyboardButton', 'KeyboardButtonPollType', 'ReplyKeyboardRemove', 'InlineKeyboardMarkup',
    'InlineKeyboardButton', 'LoginUrl', 'CallbackQuery', 'ForceReply',
    'ChatPhoto', 'ChatInviteLink', 'ChatAdministratorRights', 'ChatMember',
    'ChatMemberOwner', 'ChatMemberAdministrator', 'ChatMemberMember', 'ChatMemberRestricted',
    'ChatMemberLeft', 'ChatMemberBanned', 'ChatMemberUpdated', 'ChatJoinRequest',
    'ChatPermissions', 'ChatLocation', 'BotCommand', 'BotCommandScope',
    'BotCommandScopeDefault', 'BotCommandScopeAllPrivateChats', 'BotCommandScopeAllGroupChats', 'BotCommandScopeAllChatAdministrators',
    'BotCommandScopeChat', 'BotCommandScopeChatAdministrators', 'BotCommandScopeChatMember', 'MenuButton',
    'MenuButtonCommands', 'MenuButtonWebApp', 'MenuButtonDefault', 'ResponseParameters',
    'InputMedia', 'InputMediaPhoto', 'InputMediaVideo', 'InputMediaAnimation',
    'InputMediaAudio', 'InputMediaDocument', 'InputFile', 'Sticker',
    'StickerSet', 'MaskPosition', 'InlineQuery', 'InlineQueryResult',
    'InlineQueryResultArticle', 'InlineQueryResultPhoto', 'InlineQueryResultGif', 'InlineQueryResultMpeg4Gif',
    'InlineQueryResultVideo', 'InlineQueryResultAudio', 'InlineQueryResultVoice', 'InlineQueryResultDocument',
    'InlineQueryResultLocation', 'InlineQueryResultVenue', 'InlineQueryResultContact', 'InlineQueryResultGame',
    'InlineQueryResultCachedPhoto', 'InlineQueryResultCachedGif', 'InlineQueryResultCachedMpeg4Gif', 'InlineQueryResultCachedSticker',
    'InlineQueryResultCachedDocument', 'InlineQueryResultCachedVideo', 'InlineQueryResultCachedVoice', 'InlineQueryResultCachedAudio',
    'InputMessageContent', 'InputTextMessageContent', 'InputLocationMessageContent', 'InputVenueMessageContent',
    'InputContactMessageContent', 'InputInvoiceMessageContent', 'ChosenInlineResult', 'SentWebAppMessage',
    'LabeledPrice', 'Invoice', 'ShippingAddress', 'OrderInfo',
    'ShippingOption', 'SuccessfulPayment', 'ShippingQuery', 'PreCheckoutQuery',
    'PassportData', 'PassportFile', 'EncryptedPassportElement', 'EncryptedCredentials',
    'PassportElementError', 'PassportElementErrorDataField', 'PassportElementErrorFrontSide', 'PassportElementErrorReverseSide',
    'PassportElementErrorSelfie', 'PassportElementErrorFile', 'PassportElementErrorFiles', 'PassportElementErrorTranslationFile',
    'PassportElementErrorTranslationFiles', 'PassportElementErrorUnspecified', 'Game', 'CallbackGame',
    'GameHighScore'
]

